### ISSUE TITLE
Use separate template files instead of string constants

### ISSUE THREAD

**Issue by Feresey** [romshark/goesgen#1]
How about putting templates in a separate directory as files and use [`template.ParseGlob`](https://golang.org/pkg/html/template/#ParseGlob) instead?

Also consider using `{{- end}}`. It's better to have the template being well formatted.

**Comment by romshark** [comment]
Separate template files would mean I'd have to distribute them together with the executable, which I try to avoid.
[File-embedding is still a proposal](https://go.googlesource.com/proposal/+/master/design/draft-embed.md) and not yet standardized. I'd have to use tools like [markbates/pkger](https://github.com/markbates/pkger) which would have introduced additional complexity I don't necessarily see the value of.

`{{- end}}` looks nice though, I gotta try it, thanks!.
