### ISSUE TITLE
Update outdated example

### ISSUE THREAD

**Issue by shadowspore** [romshark/goesgen#5]
Hello friend!
Seems your schema in ```testpkg``` folder is invalid.
When I try to generate the code, Im getting these error:
```
parsing schema/source: syntax error: parsing schema file (schema.yml): yaml: unmarshal errors:
  line 75: field parameters not found in type gen.ModelMethod
  line 83: field paramters not found in type gen.ModelMethod
  line 89: field parameters not found in type gen.ModelMethod
  line 95: field parameters not found in type gen.ModelMethod
  line 102: field parameters not found in type gen.ModelMethod
  line 109: field parameters not found in type gen.ModelMethod
```
Probably need to bring the scheme up to date or smth like that, ya

**Comment by romshark** [comment]
`testpkg` was removed, we now have a working example instead: [tickets](https://github.com/romshark/goesgen/tree/402da1275e477747496efdadf06e926a3f8ef068/example/tickets)
